import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { Providers } from "./providers";
import { cn } from "@/utils/cn";
import { ReactQueryProvider } from "./queryclient";
import { SessionProvider } from "next-auth/react";
import { ToasterProvider } from "@/contexts/ToasterContext";
import AppShell from "@/components/commons/AppShell";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Layout Global",
  description: "Generated by create next app",
  icons: {
    icon: "/images/general/logo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className)}>
        <SessionProvider>
          <ReactQueryProvider>
            <Providers>
              <ToasterProvider>
                <AppShell>{children}</AppShell>
              </ToasterProvider>
            </Providers>
          </ReactQueryProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
